name: Push (main)

on:
  push:
    branches:
      - main

jobs:
  test-python:
    uses: ./.github/workflows/test-python.yml
  build:
    uses: ./.github/workflows/build-snap.yml
  publish:
    uses: ./.github/workflows/publish-snap.yml
    needs: build
    with:
      snap-path: ${{ needs.build.outputs.snap }}
