name: Push (main)

on:
  push:
    branches:
      - main

jobs:
  test-python:
    uses: ./.github/workflows/test-python.yml
  build:
    uses: ./.github/workflows/build-snap.yml
  publish:
    uses: ./.github/workflows/publish-snap.yml
    secrets: inherit
    needs:
      - test-python
      - build
    with:
      snap-amd64-path: ${{ needs.build.outputs.snap-amd64 }}
      snap-arm64-path: ${{ needs.build.outputs.snap-amd64 }}
