name: Publish Snap to edge

on:
  workflow_call:
    inputs:
      snap-amd64-path:
        type: string
        required: false
      snap-arm64-path:
        type: string
        required: false
    secrets:
      SNAPCRAFT_CREDENTIALS:
        required: true

jobs:
  publish-amd64:
    name: Publish snap amd64
    runs-on: ubuntu-latest
    steps:
      - name: Download snap artifact
        id: download
        uses: actions/download-artifact@v4
        with:
          name: local-${{ inputs.snap-amd64-path }}
      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_CREDENTIALS }}
        with:
          snap: ${{ inputs.snap-amd64-path }}
          release: edge

  publish-arm64:
    name: Publish snap arm64
    runs-on: ubuntu-latest
    if: ${{ inputs.snap-arm64-path != '' }}
    steps:
      - name: Download snap artifact
        id: download
        uses: actions/download-artifact@v4
        with:
          name: local-${{ inputs.snap-arm64-path }}
      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_CREDENTIALS }}
        with:
          snap: ${{ inputs.snap-arm64-path }}
          release: edge
